sensor:
  imu_topic: "/vectornav/IMU" # "/vectornav/IMU" "/livox/imu"
  lidar_topic: "/livox/lidar"
  cam_topic: "/camera/image_color/compressed" # "/camera/image_color" "/camera/image_color/compressed"
  
setting:
  imu_hz: 200
  lidar_hz: 10
  cam_hz: 30
  img_is_compressed: true
